#!/bin/bash

#PBS -l nodes=1:ppn=1,vmem=50gb,walltime=10:00:00
#PBS -N app-align_HCP_to_native_space
#PBS -V

raw_dir=$(jq -r .raw_dir config.json)
bold=$(jq -r .bold config.json)
sbref=$(jq -r .sbref config.json)

mkdir aligned_vols

time singularity exec -e docker://brainlife/fsl:5.0.9 ./align.sh "$raw_dir" "$bold" "$sbref"
